### ISSUE TITLE
data integrity: two dolos blocks have the same block height

### ISSUE THREAD

**Issue by alekswithakayy** [txpipe/dolos#197] opened 2024-04-11 16:48 UTC
The following blocks have the same block height / block number when fetched from dolos:

```
[1814399,"b19e4920dabd9668427d930f94ee866554b4f63e37dde2dae6bc05e343366bb2"]
[1814400,"8284fc4fe9f2f5d055b74d09bceb3bef40b8e8641096d52b224e655f03c3db28"]
```

**Comment by scarmuega** [comment] 2024-04-12 10:22
@alekswithakayy you mean when fetched through `DumpHistory`?

**Comment by scarmuega** [comment] 2024-04-12 10:30
@alekswithakayy I believe that's Byron EBB block

**Comment by alekswithakayy** [comment] 2024-04-12 14:12
Yes it happens at the epoch boundary. However, I've now synced 6 million blocks and this seems to be the only instance of it happening which is frustrating.

Any ideas why? Based on what I just read, EBBs happen at every epoch boundary in byron.

**Comment by scarmuega** [comment] 2024-06-08 21:55
@alekswithakayy do you still see inconsistencies on v0.9?

I can't reproduce on my side. Correct behavior is to see EBB blocks between each epoch throughout the Byron era.

**Comment by scarmuega** [comment] 2024-07-07 13:49
@alekswithakayy I will close this for now but feel free to re-open if you find a way to reproduce it.

**Closed by scarmuega** 2024-07-07 13:49 UTC
